const LOWEST_BASE_END: number = 8000;
const LOWEST_BASE_FREE_AMOUNT = 1360;

const FIRST_GRADE_END: number = 13000;
const FIRST_GRADE_MULTIPLIER: number = 834.88;
const FIRST_GRADE_DIVIDER: number = 5000;

const SECOND_GRADE_END: number = 85528;
const SECOND_GRADE_FREE_AMOUNT: number = 525.12;

const THIRD_GRADE_END: number = 127000;
const THIRD_GRADE_MULTIPLIER: number = SECOND_GRADE_FREE_AMOUNT;
const THIRD_GRADE_DIVIDER: number = 41472;

const FIRST_TAX_THRESHOLD = 0.1775;
const SECOND_TAX_THRESHOLD = 0.32;

const MAX_TAX_FROM_FIRST_THRESHOLD = 15181.22;

export {
  LOWEST_BASE_END,
  FIRST_GRADE_END,
  FIRST_GRADE_MULTIPLIER,
  FIRST_GRADE_DIVIDER,
  LOWEST_BASE_FREE_AMOUNT,
  SECOND_GRADE_END,
  SECOND_GRADE_FREE_AMOUNT,
  THIRD_GRADE_END,
  THIRD_GRADE_MULTIPLIER,
  THIRD_GRADE_DIVIDER,
  FIRST_TAX_THRESHOLD,
  SECOND_TAX_THRESHOLD,
  MAX_TAX_FROM_FIRST_THRESHOLD
};
