const LOWEST_BASE_END: number = 8000;
const LOWEST_BASE_FREE_AMOUNT = 13000;

const FIRST_GRADE_END: number = 13000;
const FIRST_GRADE_FREE_AMOUNT: number = 13000; // TODO

const SECOND_GRADE_END: number = 85528;
const SECOND_GRADE_FREE_AMOUNT: number = 525.12;

const THIRD_GRADE_END: number = 127000;
const THIRD_GRADE_FREE_AMOUNT: number = 525.12; // TODO

export {
  LOWEST_BASE_END,
  FIRST_GRADE_END,
  FIRST_GRADE_FREE_AMOUNT,
  LOWEST_BASE_FREE_AMOUNT,
  SECOND_GRADE_END,
  SECOND_GRADE_FREE_AMOUNT,
  THIRD_GRADE_END,
  THIRD_GRADE_FREE_AMOUNT
};
